apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-build-ci
spec:
  containers:
    - name: maven
      image: maven:alpine
      command:
        - cat
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/
    - name: docker-tools
      image: rmkanda/docker-tools:latest
      env:
      - name: DOCKLE_USERNAME
        valueFrom:
          secretKeyRef:
            name: dockerhubcred
            key: username
            optional: false
      - name: DOCKLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dockerhubcred
            key: password
            optional: false
      - name: DOCKLE_AUTH_URL
        valueFrom:
          secretKeyRef:
            name: dockerhubcred
            key: dockerurl
            optional: false
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run
          name: docker-sock
        - mountPath: /tmp/trivycache/
          name: trivycache
    - name: trufflehog
      image: rmkanda/trufflehog
      command:
        - cat
      tty: true
    - name: licensefinder
      image: licensefinder/license_finder
      command:
        - cat
      tty: true
    - name: slscan
      image: shiftleft/sast-scan
      imagePullPolicy: Always
      command:
      - cat
      tty: true
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.6.0-debug
      imagePullPolicy: Always
      command:
      - sleep
      args:
      - 99d
      volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  volumes:
    - name: m2
      hostPath:
        path: /tmp/.m2/
    - name: docker-sock
      hostPath:
        path: /var/run
    - name: trivycache
      hostPath:
        path: /tmp/trivycache/
    - name: jenkins-docker-cfg
      configMap:
        name: regcred
      #      projected:
      #  sources:
      #  - secret:
      #      name: regcred
      #      items:
      #      - key: .dockerconfigjson
      #        path: config.json
