apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dso-demo
  name: dso-demo
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dso-demo
  template:
    metadata:
      labels:
        app: dso-demo
    spec:
      volumes:
      - name: temp-storage
        emptyDir: {}
      containers:
      - image: rotimi98/dso-demo:v7
        name: dso-demo
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
        ports:
        - containerPort: 8080
        securityContext:
                #seccompProfile:
                #type: RuntimeDefault
          capabilities:
            drop:
            - all
              #  - index("ALL")
          runAsUser: 11000
          runAsGroup: 30000
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
        volumeMounts:  
        - name: temp-storage
          mountPath: /tmp
